// ============================================================================
//  auv_control/auv_params.hpp
//
//  Physical / geometric parameters for the AUV and the thrust-allocation
//  configuration matrix B (Eq. 26 of Zhang et al., Sensors 24, 3029).
//
//  Control layout:
//      u = [u1 u2 u3 u4]^T   (four actuator channels)
//      tau = [tau_x tau_y tau_z tau_m tau_n]^T  (body-frame wrench)
//      tau = B * u
//
//      with B (5x4):
//
//          | l*cos(alpha)   cos(alpha)   cos(beta)    cos(beta)  |
//          | sin(alpha)     cos(alpha)   0            0          |
//          | 0              0            cos(beta)    sin(beta)  |
//          | A              A            A            A          |
//          | B_arm          B_arm        B_arm        B_arm      |
//
//      where A = (b/2)*sin(alpha) + (a/2)*cos(alpha)
//            B_arm = (b/2)*cos(beta) + (a/2)*sin(beta).
//
//  The paper leaves alpha, beta, a, b, l as geometric constants of the
//  propulsion system. We pick values consistent with a small torpedo AUV.
// ============================================================================
#ifndef AUV_CONTROL__AUV_PARAMS_HPP_
#define AUV_CONTROL__AUV_PARAMS_HPP_

#include <Eigen/Dense>

namespace auv_control {

// ---- Shared small-vector types (used by every block) ----------------------
using StateVec   = Eigen::Matrix<double, 5, 1>;   // [u v w q r]
using ControlVec = Eigen::Matrix<double, 4, 1>;   // [u1 u2 u3 u4]
using WrenchVec  = Eigen::Matrix<double, 5, 1>;   // [tau_x tau_y tau_z tau_m tau_n]

// ---- Vehicle mass / buoyancy parameters ------------------------------------
// Matches the URDF in auv_description (~22 kg hull + ~3.2 kg thrusters).
struct VehicleParams {
  double mass            = 25.0;    // kg
  double buoyancy_force  = 25.0 * 9.81 * 1.01;  // slightly positive buoyancy, N
  double gravity         = 9.81;    // m/s^2

  // Linear drag (diagonal) coefficients Xu, Yv, Zw, Mq, Nr in body frame.
  // Chosen so the AUV reaches ~1.5 m/s cruising with ~50 N surge thrust.
  double drag_u = 25.0;
  double drag_v = 60.0;
  double drag_w = 60.0;
  double drag_p = 5.0;
  double drag_q = 15.0;
  double drag_r = 15.0;

  // Quadratic drag (|v|*v terms)
  double drag_uu = 10.0;
  double drag_vv = 40.0;
  double drag_ww = 40.0;
  double drag_qq = 4.0;
  double drag_rr = 4.0;

  // Maximum thruster output (N) — used as saturation limit in QP.
  double thrust_max = 50.0;
  double thrust_min = -50.0;

  // Max norm per channel for virtual u (N before allocation scaling).
  // Matches the "Amplitude 1..2" range used in the paper's figures.
  double u_scale = 25.0;
};

// ---- Thrust-allocation geometry --------------------------------------------
struct AllocParams {
  double alpha = 0.35;   // rad, half-angle of horizontal thruster splay
  double beta  = 0.35;   // rad, half-angle of vertical thruster splay
  // Lateral / vertical thruster arms. The original 0.10 m was much smaller
  // than a real torpedo (typical 0.2-0.4 m), which combined with Nr=15
  // capped the realizable yaw rate at ~0.21 rad/s (3x below what the
  // outer loop was commanding). Tripled to 0.30 m to give the controller
  // the moment authority it asks for.
  double a     = 0.30;   // m, lateral arm
  double b     = 0.30;   // m, vertical arm
  double l     = 1.00;   // dimensionless scale on tau_x (paper uses symbol "l")
};

// Build the 5x4 configuration matrix B from the geometric parameters.
//
// The original repo printed pitch and yaw rows as uniform across all four
// channels (A,A,A,A / Ba,Ba,Ba,Ba). That collapses the two moment axes onto
// the same scalar (u1+u2+u3+u4), so the controller cannot drive pitch and
// yaw independently and the rotational authority is whatever residual
// scalar the allocator happens to leave. We restore differential signs so
// each moment axis is generated by a real torque-couple between channels:
//
//   tau_m = A  * ( -u1 + u2 - u3 + u4 )    (pitch couple)
//   tau_n = Ba * ( +u1 - u2 - u3 + u4 )    (yaw couple)
//
// This keeps the redundancy the fault-tolerant allocator needs (every
// healthy channel still has two ways to contribute to the wrench) while
// making the rotational subspace actually controllable.
inline Eigen::Matrix<double, 5, 4> build_B(const AllocParams & g) {
  const double ca = std::cos(g.alpha), sa = std::sin(g.alpha);
  const double cb = std::cos(g.beta),  sb = std::sin(g.beta);
  const double A  = 0.5 * g.b * sa + 0.5 * g.a * ca;
  const double Ba = 0.5 * g.b * cb + 0.5 * g.a * sb;

  // Physical 4-thruster torpedo layout:
  //   u1, u2: port/stbd surge thrusters at the aft. Collective fire ->
  //           tau_x (surge force). Differential fire -> tau_n (yaw moment
  //           via the lateral lever arm Ba).
  //   u3, u4: top/bottom (or fore/aft) heave thrusters. Collective fire
  //           -> tau_z (heave force). Differential fire -> tau_m (pitch
  //           moment via the vertical lever arm A).
  // The original B had every channel contributing to every axis with
  // mixed coefficients (and pitch/yaw rows degenerated to the same
  // scalar). That made the controller's per-channel K gains chase the
  // wrong axis: ts_fuzzy.cpp says K(1,2)=kw (heave error -> u2), but the
  // old B had B(2,1)=0 (u2 produced no tau_z), so a heave command
  // produced only surge force. This new B aligns the columns with the
  // way ts_fuzzy.cpp now decomposes each channel.
  Eigen::Matrix<double, 5, 4> B;
  B << ca,    ca,    0.0,   0.0,
       0.0,   0.0,   0.0,   0.0,
       0.0,   0.0,   cb,    cb,
       0.0,   0.0,   A,    -A,
       Ba,   -Ba,    0.0,   0.0;
  return B;
}

}  // namespace auv_control

#endif  // AUV_CONTROL__AUV_PARAMS_HPP_
